Facebook/Controllers/ProfileController.cs
using Facebook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Facebook.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        string userId;
        public ProfileController() {
            userId =System.Web.HttpContext.Current.User.Identity.GetUserId();

        }
        ApplicationDbContext db = new ApplicationDbContext();
        // de 3ashn lw feh ay Object n3mlo Delete //
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        // GET: Profile
        public ActionResult Index()
        {
            userId = System.Web.HttpContext.Current.User.Identity.GetUserId();

            return View(db.Users.FirstOrDefault(o=>o.Id==userId));
        }
        #region Post
        [HttpGet]
        public ActionResult CreatePost()
        {
            userId = System.Web.HttpContext.Current.User.Identity.GetUserId();

            ViewBag.UserImage = (db.Users.FirstOrDefault(o => o.Id == userId)).image;
            return PartialView();
        }
        [HttpPost]
        public ActionResult CreatePost(Post post,bool Home)
        {
            if (ModelState.IsValid)
            {
                
                post.UserId = userId;

                db.post.Add(post);

                db.like.Add(new Like
                {
                    PostID = post.PostId,
                    LikeCounter = 0,
                    Id = userId
                });
                db.SaveChanges();
            }
         
            return RedirectToAction("GetAll_Posts");

        }
        public ActionResult GetAll_Posts()
        {
            List<Post> UserPosts = new List<Post>();
            UserPosts = db.post.Where(s => s.Deleted == false && s.UserId == userId).OrderByDescending(o=>o.Post_Date).ToList();
            //inner join with comments and likes corresponding  to this post
            return PartialView(UserPosts);
        }
  
        public ActionResult EditPost(int Id)
        {
            Post p = db.post.Include("ApplicationUser").FirstOrDefault(pp => pp.PostId == Id);
            return PartialView(p);
        }
        [HttpPost]
        public ActionResult EditPosts(Post post)
        {
            // lazem a3ml edit 3la kol Attributes maynf3sh a3ml object l2n kda hyb2a Reference //
            Post p = db.post.FirstOrDefault(pp => pp.PostId == post.PostId);
            p.Post_Body = post.Post_Body;
            //p.Post_Date = post.Post_Date;
            db.SaveChanges();
        
                return RedirectToAction("GetAll_Posts");
        }


        [HttpGet]
        public ActionResult DeletePost(int Id)
        {
            Post p = db.post.FirstOrDefault(pp => pp.PostId == Id);
            p.Deleted = true;
            db.SaveChanges();
          
                return RedirectToAction("GetAll_Posts");
        }
        #endregion

        #region Comment
        [HttpGet]
        public ActionResult CreateComent(int postid)
        {

            ViewBag.PostID = postid;
            ViewBag.Image = (db.Users.FirstOrDefault(o => o.Id == userId)).image;
            return PartialView();
        }
        [HttpPost]
        public ActionResult CreateComment(int PostID, string Comment_Body)
        {
            db.comment.Add(new Comment()
            {
                Comment_Body = Comment_Body,
                Post_ID = PostID,
                Id= userId
            });
            db.SaveChanges();
       
                return RedirectToAction("GetAll_Posts");
        }
        public ActionResult GetCommentByPostID(int PostID)
        {
            
           List<Comment>Comments=db.comment.Include("ApplicationUser").Where(o => o.Post_ID == PostID).OrderByDescending(o=>o.Comment_Date).Take(10).ToList();
            
            return PartialView(Comments);
        }

        public ActionResult Like(int PostId)
        {

            db.like.FirstOrDefault(s => s.PostID == PostId).LikeCounter+=1;
            db.SaveChanges();
         
                return RedirectToAction("GetAll_Posts");
        }
        #endregion

        #region UserBioInfo

        #region Skills
        [HttpPost]
        public ActionResult create_skill(string skill)
        {
            
            Skill s = new Skill()
            {
                skill = skill,
                UserId = userId
            };
            db.skill.Add(s);
            db.SaveChanges();
            List<Skill> l = db.skill.Where(m => m.UserId == userId).ToList();

            return PartialView("GetAllSkills",l);
        }
        [HttpPost]
        public ActionResult delete_skill(int id)
        {
            db.skill.Remove(db.skill.FirstOrDefault(m => m.ID == id ));
            db.SaveChanges();
            List<Skill> l = db.skill.Where(m => m.UserId == userId).ToList();

            return PartialView("GetAllSkills",l);
        }
        public ActionResult update_skill(int id)
        {
            var res = db.skill.FirstOrDefault(m => m.ID == id);
           
            return PartialView(res);
        }

        [HttpPost]
        public ActionResult updateskill(string skill,int id)
        {
            var res = db.skill.FirstOrDefault(m =>m.ID == id);
            res.skill = skill;
            db.SaveChanges();
            List<Skill> l = db.skill.Where(m => m.UserId == userId).ToList();

            return PartialView("GetAllSkills",l);
        }
        public ActionResult GetAllSkills()
        {
            List<Skill> l = db.skill.Where(m => m.UserId == userId).ToList();
            return PartialView(l);
        }
        #endregion

        #region Education
        public ActionResult CreateEducation(string EDU)
        {
            Education e = new Education()
            {
                UserId = userId,
                education = EDU
                
            };
            db.education.Add(e);
            db.SaveChanges();
            List<Education> l = db.education.Where(m => m.UserId == userId).ToList();

            return PartialView("GetAllEducation",l);
        }

        public ActionResult GetAllEducation()
        {
            List<Education> l = db.education.Where(m => m.UserId == userId).ToList();
            return PartialView(l);
        }

        public ActionResult delete_education(int id)
        {
            db.education.Remove(db.education.FirstOrDefault(m => m.EDUid == id ));
            db.SaveChanges();
            List<Education> edulist = db.education.Where(o => o.UserId == userId).ToList();
            return PartialView("GetAllEducation", edulist);
        }

        public ActionResult update_EDU(int id)
        {
            var res = db.education.FirstOrDefault(m => m.EDUid == id);

            return PartialView(res);
        }

        [HttpPost]
        public ActionResult updateEDU(string education, int id)
        {
            var res = db.education.FirstOrDefault(m => m.EDUid == id);
            res.education = education;
            db.SaveChanges();
            List<Education> edu = db.education.Where(o => o.UserId == userId).ToList();
            return PartialView("GetAllEducation", edu);
        }
        #endregion

        #region Work
        public ActionResult CreateWork(string work)
        {
            Work e = new Work()
            {
                UserId = userId,
                work = work
            };
            db.work.Add(e);
            db.SaveChanges();
            List<Work> l = db.work.Where(m => m.UserId == userId).ToList();

            return PartialView("GetAllWork",l);
        }

        public ActionResult GetAllWork()
        {
            List<Work> l = db.work.Where(m => m.UserId == userId).ToList();

            return PartialView(l);
        }
        public ActionResult delete_work(int id)
        {
            db.work.Remove(db.work.FirstOrDefault(m => m.id == id ));
            db.SaveChanges();
            List<Work> l = db.work.Where(m => m.UserId == userId).ToList();

            return PartialView("GetAllWork", l);
        }

        public ActionResult update_Work(int id)
        {
            var res = db.work.FirstOrDefault(m => m.id == id);

            return PartialView(res);
        }

        [HttpPost]
        public ActionResult updatework(string work, int id)
        {
            var res = db.work.FirstOrDefault(m => m.id == id);
            res.work = work;
            db.SaveChanges();
           List<Work> WorkList = db.work.Where(m => m.UserId == userId).ToList();
            return PartialView("GetAllWork", WorkList);
        }
        #endregion

        #endregion

    }

}

Facebook/Controllers/UserController.cs
using Facebook.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Facebook.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        List<Education> UserEducations = new List<Education>();
        List<Skill> UserSkills = new List<Skill>();
        List<Work> UserWorks = new List<Work>();
        List<Post> UserPosts = new List<Post>();
        ApplicationUser CurrentUser = new ApplicationUser();


        public ActionResult ShowFriendProfile(string FriendId)
        {
            bool Confirm = false;
            bool Sended = false;
            Session["friendid"] = FriendId;
            string CurrenUserID = System.Web.HttpContext.Current.User.Identity.GetUserId();
            ViewBag.currentID = (db.Users.FirstOrDefault(o => o.Id == CurrenUserID)).Id;
            var InFriendRequest = db.FriendRequests.FirstOrDefault(f => f.UserID == CurrenUserID && f.ReqFriendID==FriendId);
            var InFriendRequest2 = db.FriendRequests.FirstOrDefault(f => f.UserID == FriendId && f.ReqFriendID== CurrenUserID);
            if (InFriendRequest != null)
            {
                Confirm = InFriendRequest.Confirm;
                Sended = InFriendRequest.Sended;
            }
            else if (InFriendRequest2 != null)
            {
                Confirm = InFriendRequest2.Confirm;
                Sended = InFriendRequest2.Sended;
            }
            if (Sended == true && Confirm == false)
            {
                ViewBag.btnAddFriendTxt = "Responding";
            }
            else if (Sended == true && Confirm == true)
            {
                ViewBag.btnAddFriendTxt = "Friends";
            }
            else if (Sended == false && Confirm == false)
            {
                ViewBag.btnAddFriendTxt = "AddFriend";
            }
                return View(db.Users.FirstOrDefault(F => F.Id == FriendId));
        }
        public ActionResult GetallFriendPosts()
        {

            string FriendID = Session["friendid"].ToString();
            UserPosts = db.post.Where(p => p.UserId == FriendID && p.Deleted == false).OrderByDescending(o => o.Post_Date).ToList();
            ViewBag.currentUser =CurrentUser;
            return PartialView(UserPosts);
        }

        public ActionResult GetAllWork()
        {

            string FriendID = Session["friendid"].ToString();
          UserWorks = db.work.Where(w => w.UserId == FriendID).ToList();

            return PartialView(UserWorks);
        }

        public ActionResult GetAllEducation()
        {
            string FriendID = Session["friendid"].ToString();
            UserEducations = db.education.Where(e => e.UserId == FriendID).ToList();

            return PartialView(UserEducations);
        }

        public ActionResult GetAllSkills()
        {
            string FriendID = Session["friendid"].ToString();

            UserSkills = db.skill.Where(s => s.UserId == FriendID).ToList();
            return PartialView(UserSkills);
        }

        public ActionResult CreateComent(int postid)
        {
            ViewBag.PostID = postid;
            string uId = System.Web.HttpContext.Current.User.Identity.GetUserId();

            ViewBag.Image = (db.Users.FirstOrDefault(o => o.Id == uId)).image;
            return PartialView();
        }
        [HttpPost]
        public ActionResult CreateComment(int PostID, string Comment_Body)
        {
            string uId = System.Web.HttpContext.Current.User.Identity.GetUserId();


            db.comment.Add(new Comment()
            {
                Comment_Body = Comment_Body,
                Post_ID = PostID,
                Id = uId
            });
            db.SaveChanges();
            return RedirectToAction("GetallFriendPosts");
        }
        [HttpPost]
        public ActionResult AddFriendRequest(string user,string UserFriend)
        {
            FriendRequest friendRequest = new FriendRequest();
            friendRequest.UserID = user;
            friendRequest.ReqFriendID = UserFriend;
            friendRequest.Sended = true;
            friendRequest.Confirm = false;
            db.FriendRequests.Add(friendRequest);
            db.SaveChanges();
            return View("ShowFriendProfile");
        }

        public ActionResult allFreindRequests(string user)
        {
            List<string> Requests = (db.FriendRequests.Where(o => o.ReqFriendID == user && o.Confirm == false && o.deleted == false).Select(o => o.UserID)).ToList();
            List<ApplicationUser> UserWhoSentTheRequest = db.Users.Where(o => Requests.Contains(o.Id)).ToList();
            return PartialView(UserWhoSentTheRequest);
            
        }

        public ActionResult AcceptFriend(string userID, string FriendID)
        {
            FriendRequest Requests = db.FriendRequests.FirstOrDefault(o => o.ReqFriendID == userID && o.UserID == FriendID && o.Confirm == false);
            Requests.Confirm = true;
            Requests.Sended = true;

            db.userFriend.Add(new UserFriend()
            {
                UserID = userID,
                FriendID = FriendID,
                Friends = true
            });
            db.SaveChanges();
            return RedirectToAction("allFreindRequests");
        }

        public ActionResult RejectFriendRequest(string userID, string FriendID)
        {
            FriendRequest Requests = db.FriendRequests.FirstOrDefault(o => o.ReqFriendID == userID && o.UserID == FriendID && o.Confirm == false);
            Requests.deleted = true;
            Requests.Confirm = false;
            Requests.Sended = false;
            db.SaveChanges();
            return RedirectToAction("allFreindRequests", routeValues: new { user = userID });
        }

    }
}

Facebook/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Facebook/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Facebook/Views/Home/CreateComent.cshtml
@model Facebook.Models.Comment

@using (Ajax.BeginForm("CreateComment",  routeValues: new { PostID = ViewBag.PostID }, ajaxOptions: new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "HomeGetAllPostsDiv_", OnSuccess = "SuccessComment()" }, htmlAttributes: new { @class = "createCommentForm" }))
{

    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div id="Comment-modal-body-Div">
            <div class="col-12">
                <img id="Post-modal-body-img" src="~/Image/@ViewBag.Image" />
                @Html.TextAreaFor(model => model.Comment_Body, new { @class = "w3-border w3-padding", id = "Post-modal-body-txt", @placeholder = "Write Comment..." })
                @Html.ValidationMessageFor(model => model.Comment_Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Comment</button>
        </div>
    </div>
}

Facebook/Views/Home/CreatePost.cshtml
@model Facebook.Models.Post

@using (Ajax.BeginForm("CreatePost", ajaxOptions: new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "HomeGetAllPostsDiv_", InsertionMode = InsertionMode.Replace, OnSuccess = "fun()" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })



        <input value="false" type="hidden" name="Home" />
        <div id="Post-modal-body-Div">
            <div class="col-12">
                <img id="Post-modal-body-img" src="~/Image/@ViewBag.UserImage" />
                @Html.TextAreaFor(model => model.Post_Body, new { @class = "w3-border w3-padding", id = "Post-modal-body-txt", @placeholder = "What's In Your Mind?" })
                @Html.ValidationMessageFor(model => model.Post_Body, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Post</button>
        </div>
    </div>
}

Facebook/Views/Home/EditPost.cshtml
@model Facebook.Models.Post

@using (Ajax.BeginForm("EditPosts", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "HomeGetAllPostsDiv_", InsertionMode = InsertionMode.Replace, OnSuccess = "fun2()" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })



        @Html.HiddenFor(model => model.PostId)
        <div id="Post-modal-body-Div">
            <div class="col-12">
                <img id="Post-modal-body-img" src="~/Image/@Model.ApplicationUser.image" />
                @Html.TextAreaFor(model => model.Post_Body, new { @class = "w3-border w3-padding", id = "Post-modal-body-txt", @placeholder = "What's In Your Mind?" })
                @Html.ValidationMessageFor(model => model.Post_Body, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Post</button>
        </div>
    </div>
}

Facebook/Views/Home/GetCommentByPostID.cshtml
@model IEnumerable<Facebook.Models.Comment>

<ul class="list-group list-group-flush" style="width:20rem">

    @foreach (var item in Model)
    {

        <li class="list-group-item" style="background-color:#FAFAFA;width:400px;border:none">
            <img src="~/Image/@item.ApplicationUser.image" style="width:40px; border-radius:100%" />
            <label>@item.ApplicationUser.UserName</label>
            <input type="text" readonly value="@item.Comment_Body" style="display:inline-block;background-color:#EEEEEE;height:30px;width:85%;border-radius:20px;padding-left:10px;border:1px solid #BDBDBD;" class="w3-border w3-padding">
        </li>



    }

</ul>

Facebook/Views/Home/HomePosts.cshtml
@model IEnumerable<Facebook.Models.Post>


@{int counter = 0;
    foreach (var item in Model)
    {




        <!--posts-->
        <div id="PostsTimeLine" class="container-fluid col-12 modal-content">

            <div>
                <div>
                    <img src="~/Image/@item.ApplicationUser.image" />

                    <div id="PostUserInfo">
                        <span class="PostUserName">@item.ApplicationUser.Name</span>
                        <span class="PostDate">@item.Post_Date</span>
                    </div>
                    <div style="display:inline-block;float:right;margin-top:10px;margin-right:30px">
                        @if (ViewBag.CurrentUserID == item.UserId)
                        {
                        <a data-toggle="modal" onclick="Homeopeneditmodal(@counter)">
                            <i class="fas fa-pen-alt" style="color:dimgrey;display:inline-block;margin-right:20px;cursor:pointer"></i>
                        </a>
                        @Ajax.ActionLink(" ", "DeletePost",  routeValues: new { Id = item.PostId }, ajaxOptions: new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "HomeGetAllPostsDiv_" }, htmlAttributes: new
                          {
                                @class = "fas fa-trash ALink",
                                  style = "color:dimgrey;display:inline-block;cursor:pointer;"
                           })
                        }
                    </div>
                </div>
                <div class=".container-fluid" id="TimeLinePostBody">
                    <div>
                        <p class="PostBody">@item.Post_Body</p>
                        <hr />
                        <div id="PostBodyLikeComment">
                            <a id="Like" href="@Url.Action("Like","Profile", new { PostId = item.PostId,Home=true })">
                                <img id="PostBodyLikeasset" src="~/Image/facebook-like-black.png" />
                                <p style="display:inline-block">Like</p>
                            </a>
                            <a onclick="togglecomments(@counter)" style="cursor:pointer">
                                <img id="PostBodyCommentasset" src="~/Image/comments-black.png" />
                                <p style="display:inline-block; cursor:pointer">Comment</p>
                            </a>
                        </div>
                        <hr />
                       
                        <div id="CommentSection" class="col-12">
                            <img src="~/Image/@item.ApplicationUser.image" style="" />
                            <input type="text" onclick="fireelment(@counter)" placeholder="write a Comment..." style="" class="w3-border w3-padding ">
                        </div>
                        <hr />
                        <div class="commentsCard col-12 " id="GetallCommentsDIV" style="width: 21rem">
                            @Html.Action("GetCommentByPostID",  routeValues: new { PostID = item.PostId,Home=true })

                        </div>

                    </div>
                </div>
            </div>

        </div>


        <!--Edit Post Modat-->
        <div class="row">
            <div class="col-12">
                <div class="modal fade HomeeditModal" id="HomePostModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel2">Edit Post</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="Edit-Post-modal-body">

                                @Html.Action("EditPost", new { Id = item.PostId })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!-- CommentModal -->
        <div class="modal fade CommentsModat" id="CommentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h6 class="modal-title" id="exampleModalLabel">Create Comment</h6>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div id="Comment__Content" class="Comment-modal-body">
                        @Html.Action("CreateComent",routeValues: new { PostID = item.PostId })
                    </div>

                </div>
            </div>
        </div>


        counter++;

    }
}

Facebook/Views/Home/Index.cshtml
@model Facebook.Models.ApplicationUser

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}






<!--End  Of Profile Header-->
    <div class="row">
            <!--Left Menu-->

        <div id="LeftMainMenu" class="jumbotron jumbotron-fluid col-md-3 col-12">
            <div  id="Div_lftMenu">
                <ul class="list-group">
                    <li class="list-group-item ">
                        <span class="glyphicon glyphicon-home"> Market Place</span>
                    </li>
                    <li class="list-group-item ">
                        <span class="glyphicon glyphicon-picture"> News Feed</span>
                    </li>
                    <li class="list-group-item ">
                        <span class="glyphicon glyphicon-calendar"> Events</span>
                    </li>
                    <li class="list-group-item ">
                        <span class="glyphicon glyphicon-user">
                            <a href=""> Friends List</a>
                        </span>
                    </li>
                    <li class="list-group-item ">
                        <span class="glyphicon glyphicon-user"> Groups</span>
                    </li>
                    <li class="list-group-item ">
                        <span class="glyphicon glyphicon-facetime-video"> Watch</span>
                    </li>
                </ul>
            </div>

        </div>

            <!--CreatePost and Posts-->
            <div id="MainPostContainer" class="jumbotron jumbotron-fluid col-md-5 col-12">

                <div id="AllPostsDivContainer">

                    <!--createPost-->
                    <div id="CreatePost" class=" col-12 modal-content">
                        <p>Create Post</p>

                        <div id="CreatePostInputs">
                            <div class="col-12">
                                <img src="~/Image/@Model.image" style="" />
                                <input type="text" placeholder="What's In Your Mind,@Model.UserName ?..." class="w3-border w3-padding" data-toggle="modal" data-target="#Create_PostModal">
                            </div>
                        </div>

                    </div>
                    <div id="HomeGetAllPostsDiv_">
                        @Html.Action("HomePosts")
                    </div>

                </div>
            </div>

            <!--Right Menu-->
            <div id="RightMainMenu" class="jumbotron jumbotron-fluid col-md-3 col-12"></div>
        </div>

        <div class="row">
            <!-- CreatePostModal -->
            <div class="col-12">
                <div class="modal fade" id="Create_PostModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel2">Create Post</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="Post-modal-body">
                                @Html.Action("CreatePost")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

Facebook/Views/Home/Search.cshtml
@model IEnumerable<Facebook.Models.ApplicationUser>
<!-- Modal -->

                <table class="table">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <form class="row">
                                    <img src="~/Image/@item.image" style="width:80px;height:60px;border-radius:100%;border:5px solid white;" />
                                    @Html.ActionLink(item.UserName, "ShowFriendProfile", "User",routeValues: new{ FriendId = item.Id },htmlAttributes:new {@class="" })
                                </form>
                            </td>
                        </tr>
                    }
                </table>